<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Kodbruket\Margins\Block\Adminhtml\System\Config\Checktoken $block */
?>
<script>
require(['prototype'], function(){

//<![CDATA[
    function checkToken() {
        var validationMessage = $('check_token_result');

        params = {
            auth_url: $('<?= $block->escapeJs($block->getAuthUrl()) ?>').value,
            token: $('<?= $block->escapeJs($block->getToken()) ?>').value
        };

        new Ajax.Request('<?= $block->escapeJs($block->escapeUrl($block->getAjaxUrl())) ?>', {
            parameters: params,
            onSuccess: function(response) {
                var result = '<?= $block->escapeJs($block->escapeHtml(__('Error during Token verification.'))) ?>';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    if (response.valid == 1) {
                        validationMessage.removeClassName('hidden').addClassName('success')
                    } else {
                        validationMessage.removeClassName('hidden').addClassName('error')
                    }
                } catch (e) {
                    validationMessage.removeClassName('hidden').addClassName('error')
                }
                validationMessage.update(result);
            }
        });
    }

    window.checkToken = checkToken;
//]]>

});
</script>
<div class="actions actions-check-token">
    <div id="check_token_result" class="message-validation hidden"></div>
    <button onclick="javascript:checkToken(); return false;" class="action-validate-vat" type="button" id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
